Repository glotzerlab/garnett, pull requests merged in 2020-03, with the labels that each got.

#147 Use types and typeid properties consistent with HOOMD
  .circleci/config.yml
  README.md
  bin/garnett2pos
  changelog.rst
  doc/credits.rst
  doc/quickstart.rst
  garnett/ciffilereader.py
  garnett/ciffilewriter.py
  garnett/dcdfilereader.py
  garnett/errors.py
  garnett/getarfilereader.py
  garnett/getarfilewriter.py
  garnett/gsdhoomdfilereader.py
  garnett/gsdhoomdfilewriter.py
  garnett/hoomdxmlfilereader.py
  garnett/posfilereader.py
  garnett/posfilewriter.py
  garnett/shapes.py
  garnett/trajectory.py
  tests/files/shapes/generate_shape_data.py
  tests/test_getarfilereader.py
  tests/test_getarfilewriter.py
  tests/test_gsdhoomdfilewriter.py
  tests/test_posfilereaderwriter.py
  tests/test_shapes.py
  tests/test_trajectory.py
Labels: enhancement

#151 Improve CIF _atom_site_label type handling
  changelog.rst
  doc/credits.rst
  garnett/ciffilereader.py
  tests/test_ciffilereaderwriter.py
Labels: enhancement

#149 Enable trajectory property for box objects
  README.md
  changelog.rst
  doc/credits.rst
  doc/quickstart.rst
  garnett/dcdfilereader.py
  garnett/trajectory.py
  tests/test_trajectory.py
Labels: enhancement

#152 Update CI & Deployment
  .circleci/config.yml
  .circleci/deploy.bash
  .circleci/requirements.txt
  .deploy.bash
  .flake8
  .requirements-deploy.txt
  .test-deploy.bash
  requirements-dev.txt
  samples/encode_base64.py
Labels: enhancement

#154 Some documentation cleanup before 0.7.0.
  .coveragerc
  .flake8
  LICENSE.txt
  bin/garnett2pos
  doc/conf.py
  doc/credits.rst
  doc/quickstart.rst
  doc/readerswriters.rst
  doc/shapes.rst
  examples/example-hpmc-extended.py
  examples/example-hpmc.py
  examples/generate_gtar_sample.py
  examples/hoomd-signac-example/README.md
  examples/hoomd-signac-example/init.py
  examples/hoomd-signac-example/run.py
  examples/hoomd-signac-example/test_read.py
  examples/modify.py
  examples/test_read.py
  examples/translate.py
  garnett/ciffilereader.py
  garnett/ciffilewriter.py
  garnett/dcdfilereader.py
  garnett/errors.py
  garnett/getarfilereader.py
  garnett/getarfilewriter.py
  garnett/gsdhoomdfilereader.py
  garnett/gsdhoomdfilewriter.py
  garnett/hoomdxmlfilereader.py
  garnett/posfilereader.py
  garnett/posfilewriter.py
  garnett/pydcdreader.py
  garnett/pygsd.py
  garnett/reader.py
  garnett/samples.py
  garnett/shapes.py
  garnett/trajectory.py
  garnett/util.py
  garnett/version.py
  garnett/writer.py
  samples/encode_base64.py
  samples/write_hoomd_xml_dcd_gsd.py
  setup.py
  tests/files/shapes/generate_shape_data.py
  tests/test_ciffilereaderwriter.py
  tests/test_dcdfilereader.py
  tests/test_getarfilereader.py
  tests/test_getarfilewriter.py
  tests/test_gsdhoomdfilereader.py
  tests/test_gsdhoomdfilewriter.py
  tests/test_hoomdxmlreader.py
  tests/test_plato_scenes.py
  tests/test_posfilereaderwriter.py
  tests/test_pydcdfilereader.py
  tests/test_shapes.py
  tests/test_trajectory.py
  tests/test_util.py
Labels: documentation

#155 Revised FrameData and snapshot API, added integration tests.
  .circleci/config.yml
  changelog.rst
  doc/credits.rst
  garnett/ciffilereader.py
  garnett/trajectory.py
  tests/test_plato_scenes.py
  tests/test_trajectory.py
Labels: enhancement

#153 Fix type subsetting in to_plato_scene.
  garnett/trajectory.py
Labels: bug

#157 Clarify dependencies
  .circleci/config.yml
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/test_ciffilereaderwriter.py
  tests/test_util.py
Labels: bug
